# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kDjv9izlxjgkNco_tt5W4OKFTY3zg3qC
"""

!pip install --upgrade diffusers
!pip install transformers

!pip install accelerate

from diffusers import DiffusionPipeline
from diffusers import StableDiffusionPipeline
import torch
model_id = "prompthero/openjourney"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "a monkey wearing indian tradition cloth and riding bycycle"
image = pipe(prompt).images[0]
image.save("./retro_cars.png")

